### ISSUE TITLE
Better organize the JavaSettings

### ISSUE THREAD

**Issue by jianghaolu** [Azure/autorest.java#1190]
Today we have 40 settings in a flat list - but it may be possible to organize them better.

Approach 1: Use better naming to indicate hierarchy, e.g. `subpackage-models`, `subpackage-implementation`, `subpackage-custom-types`, `pom-artifact-id`, `pom-group-id`, etc.

Approach 2: Use YAML objects to build hierarchy, like what we are doing for `polling`:
```yaml
polling:
  {operationId}:
    strategy: {strategy}
    intermediate-type: {intermediate-type}
    final-type: {final-type}
    poll-interval: {poll-interval}
```

Similarly, we can have

```yaml
subpackage:
  models: {models-subpackage}
  implementation: {implementation-subpackage}
  custom-types: {custom-types-subpackage}
```

Or other approaches?
