### ISSUE TITLE
LLC/Client, use "security" from autorest/modelerfour

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/autorest.java#1314]
autorest doc
https://github.com/Azure/autorest/blob/main/docs/generate/authentication.md

m4 output
```yaml
security:
  authenticationRequired: true
  schemes:
    - type: AADToken
      scopes:
        - https://atlas.microsoft.com/.default
```

We should prefer security configure from autorest/m4, and avoid using our own definition of `credential-types`, `credential-scopes`, `key-credential-header-name` options (they can work as another override, but we should avoid using them whenever swagger and standard autorest option is good enough).
