### ISSUE TITLE
DPG should fix casing of parameters borrowed from OData

### ISSUE THREAD

**Issue by mikekistler** [Azure/autorest.java#1569]
The Azure REST API Guidelines recommend standard query parameters borrowed from OData. Some of these parameters have names that contain multiple words but are all lowercase run together, e.g. "orderby", "maxpagesize".

For client libraries, we want these names to be exposed as multi-word names using the appropriate language idiom, e.g. "orderBy" in .NET.

Our DPG generators (autorest-based or Cadl-based) should ensure the correct transformation of the parameter names in the REST API to idiomatic form for the target language.

**Comment by weidongxu-microsoft** [comment]
in autorest, we might ask m4 do this
```
  naming:
    choiceValue: upper
    preserve-uppercase-max-length: 2
    override:
      orderby: orderBy
```

CADL probably just us in codegen or emitter.

@srnagar  for comments.
