### ISSUE TITLE
Cadl LRO, emitter

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/autorest.java#1734]
Emitter to include e.g.

```yaml
operationLinks:
  polling: [operation1]
  final: [operation2]
```

---

likely need to copy and modify `Operation` (add above) from https://github.com/Azure/autorest m4, similar to `choice.ts`
