### ISSUE TITLE
Suppoert additionalProperties

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/autorest.java#477]
```
    "DirectoryObject": {
      "type": "object",
      "discriminator": "objectType",
      "properties": {
        "objectId": {
          "type": "string",
          "description": "The object ID.",
          "readOnly": true
        },
        "objectType": {
          "type": "string",
          "description": "The object type.",
          "readOnly": true
        },
        "deletionTimestamp": {
          "type": "string",
          "format": "date-time",
          "description": "The time at which the directory object was deleted.",
          "readOnly": true
        }
      },
      "additionalProperties": {
        "type": "object"
      },
      "description": "Represents an Azure Active Directory object."
    },
```

In YAML, DirectoryObject would have immediate parent of schema type "dictionary".

```
        parents:
          all:
          - *ref_0
          - &ref_2
            type: dictionary
            elementType:
              type: any
              language:
                default:
                  name: any
                  description: <Any object>
              protocol: {}
            language:
              default:
                name: DirectoryObject
                description: Represents an Azure Active Directory object.
            protocol: {}
          immediate:
          - *ref_0
```
