### ISSUE TITLE
Generator producing incorrect XML annotations

### ISSUE THREAD

**Issue by RikkiGibson** [Azure/autorest.java#64]
This YAML fragment declares a Block model:
```yaml
  Block:
    type: object
    required:
    - name
    - size
    description: Represents a single block in a block blob.  It describes the block's ID and size.
    properties:
      name:
        description: The base64 encoded block ID.
        type: string
        xml:
          name: Name
      size:
        description: The block size in bytes.
        type: integer
        xml:
          name: Size
```

Note that the XML property names are "Name" and "Size", while the generator produces the annotation arguments "name" and "size". We are probably failing to use the XML name in AutoRest.
https://github.com/jofriedm/JavaAsync/blob/master/src/main/java/com/microsoft/azure/storage/models/BlockList.java#L23
