### ISSUE TITLE
Enum custom types are not moved to custom-types-subpackage

### ISSUE THREAD

**Issue by conniey** [Azure/autorest.java#643]
## Steps to reproduce:
1. build v4 branch.
1. Add an enum type.
    1. Full swagger.json: https://github.com/YijunXieMS/azure-rest-api-specs-pr/blob/servicebus_mgmt/specification/servicebus/data-plane/servicebus-swagger.json
1. Generate with settings below.

## Expected
`EntityStatus` is moved to the "models" folder

## Actual
`EntityStatus` is generated in "implementations.models".

## Code
swagger.json
```json
{
  "definitions": {
    "EntityStatus": {
      "description": "Status of a Service Bus resource",
      "type": "string",
      "xml": {
        "namespace": "http://schemas.microsoft.com/netservices/2010/10/servicebus/connect"
      },
      "enum": [
        "Active",
        "Creating",
        "Deleting",
        "Disabled",
        "ReceiveDisabled",
        "Renaming",
        "Restoring",
        "SendDisabled",
        "Unknown"
      ]
    }
  }
}
```

README.md
```yaml
input-file: $azure-rest-api-specs-pr\specification\servicebus\data-plane\servicebus-swagger.json
java: true
output-folder: ..\
generate-client-as-impl: true
namespace: com.azure.messaging.servicebus
generate-client-interfaces: false
sync-methods: none
license-header: MICROSOFT_MIT_SMALL
add-context-parameter: true
models-subpackage: implementation.models
custom-types: AuthorizationRule,EntityAvailabilityStatus,EntityStatus,
custom-types-subpackage: models
context-client-method-parameter: true
enable-xml: true
```
