### ISSUE TITLE
JacksonXmlRootElement import not added for `allOf` swagger types.

### ISSUE THREAD

**Issue by conniey** [Azure/autorest.java#644]
## Steps to reproduce:
1. build v4 branch.
1. Add some types that use "allOf".
    1. Full swagger.json: https://github.com/YijunXieMS/azure-rest-api-specs-pr/blob/servicebus_mgmt/specification/servicebus/data-plane/servicebus-swagger.json
1. Generate with settings below.

## Expected
Compilable code is generated.

## Actual
Import for `@JacksonXmlRootElement` is missing, so it can't compile.

## Code
swagger.json
```json
{
  "definitions": {
    "RuleAction": {
      "type":"object",
      "discriminator": "type",
      "xml": {
        "name": "Action",
        "namespace": "http://schemas.microsoft.com/netservices/2010/10/servicebus/connect"
      },
      "properties": {
        "type": {
          "type": "string",
          "xml": {
            "attribute": true,
            "prefix": "xsi",
            "namespace": "http://www.w3.org/2001/XMLSchema-instance"
          }
        }
      }
    },
    "SqlRuleAction": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/RuleAction"
        },
        {
          "type": "object",
          "properties": {
            "SqlExpression": {
              "type": "string",
              "xml": {
                "namespace": "http://schemas.microsoft.com/netservices/2010/10/servicebus/connect"
              }
            }
          }
        }
      ]
    },
    "EmptyRuleAction": {
      "type": "object",
      "allOf": [
        {"$ref": "#/definitions/RuleAction"}
      ]
    },
  }
}
```

README.md
```yaml
input-file: $\azure-rest-api-specs-pr\specification\servicebus\data-plane\servicebus-swagger.json
java: true
output-folder: ..\
generate-client-as-impl: true
namespace: com.azure.messaging.servicebus
generate-client-interfaces: false
sync-methods: none
license-header: MICROSOFT_MIT_SMALL
add-context-parameter: true
models-subpackage: implementation.models
context-client-method-parameter: true
enable-xml: true
```
