### ISSUE TITLE
[BUG] Generator is not creating a new variable resulting in uncompilable code

### ISSUE THREAD

**Issue by gapra-msft** [Azure/autorest.java#902]
Using this swagger file

https://raw.githubusercontent.com/gapra-msft/azure-rest-api-specs/storage/queueGenerator/specification/storage/data-plane/Microsoft.BlobStorage/preview/2020-04-08/blob.json

And this swagger README

https://raw.githubusercontent.com/Azure/azure-sdk-for-java/c708ca0cf105043411598b20b7668511e0631e45/sdk/storage/azure-storage-blob/swagger/README.md

The generated code is not compilable. Basically the encryptionScope variable seems to be used twice in a bunch of the generated APIs

**Comment by gapra-msft** [comment]
BlobStorageCustomization 
https://raw.githubusercontent.com/Azure/azure-sdk-for-java/c708ca0cf105043411598b20b7668511e0631e45/sdk/storage/azure-storage-blob/swagger/src/main/java/com/azure/storage/blob/customization/BlobStorageCustomization.java

**Comment by srnagar** [comment]
@gapra-msft This issue is caused by one of the transformations that's duplicating the name `encryptionScope`.

### Rename cpk-scope-info to encryption-scope	
``` yaml	
directive:	
- from: swagger-document	
  where: $.parameters	
  transform: >	
    $.EncryptionScope["x-ms-parameter-grouping"]["name"] = "encryption-scope";	
```

If you change the transformation to the following, the generated code looks right:

### Rename cpk-scope-info to encryption-scope-group
``` yaml	
directive:	
- from: swagger-document	
  where: $.parameters	
  transform: >	
    $.EncryptionScopeGroup["x-ms-parameter-grouping"]["name"] = "encryption-scope-group";	
```

Let me know if this transformation works.
